### ISSUE TITLE
Physical data for 387 hauls from GOA and BS

### ISSUE THREAD

**Issue by NancyRoberson** [afsc-gap-products/data-requests#70] opened 2023-09-05 17:34 UTC
**Data product requested (stratum CPUE, etc.)**:  physical data for 387 hauls in attached spread sheet. [Pcod_Unique.csv](https://github.com/afsc-gap-products/data-requests/files/12526269/Pcod_Unique.csv)
**Species**: Pacific cod

**Region** (GOA, AI, Bering Sea): GOA and BS

My name is David Taylor; I received your contact information from Jon Short. I am a postdoc working with Dr. Jessica Miller at Oregon State University on her NPRB project. We are working on reconstructing cod thermal histories using stable isotope analysis of otolith carbonates. Jon directed us to you because we are hoping to get any physical data associated with the cruises and dates of capture for the fish we are analyzing. I am especially interested in any water temperature data associated with the cruises on the dates I am providing.

If it is possible to get such data, please find attached a .csv file which includes the cruise number and vessel name, fall all unique collection dates (date_collected). Please let me know if I can provide any additional information. Thank you for your time and any assistance you can provide. Take care and stay well.

**Research team making the request** David.Taylor@oregonstate.edu  Jessica.Miller@oregonstate.edu

**Comment by zoyafuso-NOAA** [comment] 2024-07-12 18:13
I will close this issue because it is a duplicate of #93, which has been completed.

**Closed by zoyafuso-NOAA** 2024-07-12 18:13 UTC
Labels: GOA, BERING
